
/*
 * Copyright Freddie Chopin 2013.
 * Distributed under the Boost Software License, Version 1.0.
 * (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
 */

/**
 * \file hdr/hdr_cgu.h
 * \brief Header with definition of bits in CGU control registers
 *
 * chip: LPC43xx
 *
 * \author Freddie Chopin, http://www.freddiechopin.pl http://www.distortec.com
 * \date 2013-04-02
 */

#ifndef HDR_HDR_I2C_H_
#define HDR_HDR_I2C_H_

#include "hdr/hdr_bitband.h"

/*---------------------------------------------------------------------------------------------------------------------+
| common
+---------------------------------------------------------------------------------------------------------------------*/

#define CGU_x_CLK_SEL_bit					24

#define CGU_x_CLK_SEL_32_kHz_value			0
#define CGU_x_CLK_SEL_IRC_value				1
#define CGU_x_CLK_SEL_ENET_RX_CLK_value		2
#define CGU_x_CLK_SEL_ENET_TX_CLK_value		3
#define CGU_x_CLK_SEL_GP_CLKIN_value		4
#define CGU_x_CLK_SEL_CRYSTAL_value			6
#define CGU_x_CLK_SEL_PLL0USB_value			7
#define CGU_x_CLK_SEL_PLL0AUDIO_value		8
#define CGU_x_CLK_SEL_PLL1_value			9
#define CGU_x_CLK_SEL_IDIVA_value			12
#define CGU_x_CLK_SEL_IDIVB_value			13
#define CGU_x_CLK_SEL_IDIVC_value			14
#define CGU_x_CLK_SEL_IDIVD_value			15
#define CGU_x_CLK_SEL_IDIVE_value			16
#define CGU_x_CLK_SEL_mask					31

#define CGU_x_CLK_SEL_32_kHz				(CGU_x_CLK_SEL_32_kHz_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_IRC					(CGU_x_CLK_SEL_IRC_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_ENET_RX_CLK			(CGU_x_CLK_SEL_ENET_RX_CLK_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_ENET_TX_CLK			(CGU_x_CLK_SEL_ENET_TX_CLK_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_GP_CLKIN				(CGU_x_CLK_SEL_GP_CLKIN_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_CRYSTAL				(CGU_x_CLK_SEL_CRYSTAL_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_PLL0USB				(CGU_x_CLK_SEL_PLL0USB_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_PLL0AUDIO				(CGU_x_CLK_SEL_PLL0AUDIO_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_PLL1					(CGU_x_CLK_SEL_PLL1_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_IDIVA					(CGU_x_CLK_SEL_IDIVA_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_IDIVB					(CGU_x_CLK_SEL_IDIVB_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_IDIVC					(CGU_x_CLK_SEL_IDIVC_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_IDIVD					(CGU_x_CLK_SEL_IDIVD_value << CGU_x_CLK_SEL_bit)
#define CGU_x_CLK_SEL_IDIVE					(CGU_x_CLK_SEL_IDIVE_value << CGU_x_CLK_SEL_bit)

/*---------------------------------------------------------------------------------------------------------------------+
| LPC_CGU_FREQ_MON - Frequency monitor register
+---------------------------------------------------------------------------------------------------------------------*/

#define CGU_FREQ_MON_MEAS_bb				BITBAND(&LPC_CGU->FREQ_MON, CGU_FREQ_MON_MEAS_Pos)

/*---------------------------------------------------------------------------------------------------------------------+
| LPC_CGU_XTAL_OSC_CTRL - Crystal oscillator control register
+---------------------------------------------------------------------------------------------------------------------*/

#define CGU_XTAL_OSC_CTRL_ENABLE_bb			BITBAND(&LPC_CGU->XTAL_OSC_CTRL, CGU_XTAL_OSC_CTRL_ENABLE_Pos)
#define CGU_XTAL_OSC_CTRL_BYPASS_bb			BITBAND(&LPC_CGU->XTAL_OSC_CTRL, CGU_XTAL_OSC_CTRL_BYPASS_Pos)
#define CGU_XTAL_OSC_CTRL_HF_bb				BITBAND(&LPC_CGU->XTAL_OSC_CTRL, CGU_XTAL_OSC_CTRL_HF_Pos)

/*---------------------------------------------------------------------------------------------------------------------+
| LPC_CGU_PLL1_STAT - PLL1 status register
+---------------------------------------------------------------------------------------------------------------------*/

#define CGU_PLL1_STAT_LOCK_bb				BITBAND(&LPC_CGU->PLL1_STAT, CGU_PLL1_STAT_LOCK_Pos)

/*---------------------------------------------------------------------------------------------------------------------+
| LPC_CGU_PLL1_CTRL - PLL1 control register
+---------------------------------------------------------------------------------------------------------------------*/

#define CGU_PLL1_CTRL_PD_bb					BITBAND(&LPC_CGU->PLL1_CTRL, CGU_PLL1_CTRL_PD_Pos)
#define CGU_PLL1_CTRL_BYPASS_bb				BITBAND(&LPC_CGU->PLL1_CTRL, CGU_PLL1_CTRL_BYPASS_Pos)
#define CGU_PLL1_CTRL_FBSEL_bb				BITBAND(&LPC_CGU->PLL1_CTRL, CGU_PLL1_CTRL_FBSEL_Pos)
#define CGU_PLL1_CTRL_DIRECT_bb				BITBAND(&LPC_CGU->PLL1_CTRL, CGU_PLL1_CTRL_DIRECT_Pos)
#define CGU_PLL1_CTRL_AUTOBLOCK_bb			BITBAND(&LPC_CGU->PLL1_CTRL, CGU_PLL1_CTRL_AUTOBLOCK_Pos)

#define CGU_PLL1_CTRL_PSEL_POSTDIV2_value	0
#define CGU_PLL1_CTRL_PSEL_POSTDIV4_value	1
#define CGU_PLL1_CTRL_PSEL_POSTDIV8_value	2
#define CGU_PLL1_CTRL_PSEL_POSTDIV16_value	3

#define CGU_PLL1_CTRL_PSEL_POSTDIV2			(CGU_PLL1_CTRL_PSEL_POSTDIV2_value << CGU_PLL1_CTRL_PSEL_Pos)
#define CGU_PLL1_CTRL_PSEL_POSTDIV4			(CGU_PLL1_CTRL_PSEL_POSTDIV4_value << CGU_PLL1_CTRL_PSEL_Pos)
#define CGU_PLL1_CTRL_PSEL_POSTDIV8			(CGU_PLL1_CTRL_PSEL_POSTDIV8_value << CGU_PLL1_CTRL_PSEL_Pos)
#define CGU_PLL1_CTRL_PSEL_POSTDIV16		(CGU_PLL1_CTRL_PSEL_POSTDIV16_value << CGU_PLL1_CTRL_PSEL_Pos)

#define CGU_PLL1_CTRL_NSEL_PREDIV1_value	0
#define CGU_PLL1_CTRL_NSEL_PREDIV2_value	1
#define CGU_PLL1_CTRL_NSEL_PREDIV3_value	2
#define CGU_PLL1_CTRL_NSEL_PREDIV4_value	3

#define CGU_PLL1_CTRL_NSEL_PREDIV1			(CGU_PLL1_CTRL_NSEL_PREDIV1_value << CGU_PLL1_CTRL_NSEL_Pos)
#define CGU_PLL1_CTRL_NSEL_PREDIV2			(CGU_PLL1_CTRL_NSEL_PREDIV2_value << CGU_PLL1_CTRL_NSEL_Pos)
#define CGU_PLL1_CTRL_NSEL_PREDIV3			(CGU_PLL1_CTRL_NSEL_PREDIV3_value << CGU_PLL1_CTRL_NSEL_Pos)
#define CGU_PLL1_CTRL_NSEL_PREDIV4			(CGU_PLL1_CTRL_NSEL_PREDIV4_value << CGU_PLL1_CTRL_NSEL_Pos)

#define CGU_PLL1_CTRL_MSEL_MUL1_value		0
#define CGU_PLL1_CTRL_MSEL_MUL2_value		1
#define CGU_PLL1_CTRL_MSEL_MUL3_value		2
#define CGU_PLL1_CTRL_MSEL_MUL4_value		3
#define CGU_PLL1_CTRL_MSEL_MUL5_value		4
#define CGU_PLL1_CTRL_MSEL_MUL6_value		5
#define CGU_PLL1_CTRL_MSEL_MUL7_value		6
#define CGU_PLL1_CTRL_MSEL_MUL8_value		7
#define CGU_PLL1_CTRL_MSEL_MUL9_value		8
#define CGU_PLL1_CTRL_MSEL_MUL10_value		9
#define CGU_PLL1_CTRL_MSEL_MUL11_value		10
#define CGU_PLL1_CTRL_MSEL_MUL12_value		11
#define CGU_PLL1_CTRL_MSEL_MUL13_value		12
#define CGU_PLL1_CTRL_MSEL_MUL14_value		13
#define CGU_PLL1_CTRL_MSEL_MUL15_value		14
#define CGU_PLL1_CTRL_MSEL_MUL16_value		15
#define CGU_PLL1_CTRL_MSEL_MUL17_value		16
#define CGU_PLL1_CTRL_MSEL_MUL18_value		17
#define CGU_PLL1_CTRL_MSEL_MUL19_value		18
#define CGU_PLL1_CTRL_MSEL_MUL20_value		19
#define CGU_PLL1_CTRL_MSEL_MUL21_value		20
#define CGU_PLL1_CTRL_MSEL_MUL22_value		21
#define CGU_PLL1_CTRL_MSEL_MUL23_value		22
#define CGU_PLL1_CTRL_MSEL_MUL24_value		23
#define CGU_PLL1_CTRL_MSEL_MUL25_value		24
#define CGU_PLL1_CTRL_MSEL_MUL26_value		25
#define CGU_PLL1_CTRL_MSEL_MUL27_value		26
#define CGU_PLL1_CTRL_MSEL_MUL28_value		27
#define CGU_PLL1_CTRL_MSEL_MUL29_value		28
#define CGU_PLL1_CTRL_MSEL_MUL30_value		29
#define CGU_PLL1_CTRL_MSEL_MUL31_value		30
#define CGU_PLL1_CTRL_MSEL_MUL32_value		31
#define CGU_PLL1_CTRL_MSEL_MUL33_value		32
#define CGU_PLL1_CTRL_MSEL_MUL34_value		33
#define CGU_PLL1_CTRL_MSEL_MUL35_value		34
#define CGU_PLL1_CTRL_MSEL_MUL36_value		35
#define CGU_PLL1_CTRL_MSEL_MUL37_value		36
#define CGU_PLL1_CTRL_MSEL_MUL38_value		37
#define CGU_PLL1_CTRL_MSEL_MUL39_value		38
#define CGU_PLL1_CTRL_MSEL_MUL40_value		39
#define CGU_PLL1_CTRL_MSEL_MUL41_value		40
#define CGU_PLL1_CTRL_MSEL_MUL42_value		41
#define CGU_PLL1_CTRL_MSEL_MUL43_value		42
#define CGU_PLL1_CTRL_MSEL_MUL44_value		43
#define CGU_PLL1_CTRL_MSEL_MUL45_value		44
#define CGU_PLL1_CTRL_MSEL_MUL46_value		45
#define CGU_PLL1_CTRL_MSEL_MUL47_value		46
#define CGU_PLL1_CTRL_MSEL_MUL48_value		47
#define CGU_PLL1_CTRL_MSEL_MUL49_value		48
#define CGU_PLL1_CTRL_MSEL_MUL50_value		49
#define CGU_PLL1_CTRL_MSEL_MUL51_value		50
#define CGU_PLL1_CTRL_MSEL_MUL52_value		51
#define CGU_PLL1_CTRL_MSEL_MUL53_value		52
#define CGU_PLL1_CTRL_MSEL_MUL54_value		53
#define CGU_PLL1_CTRL_MSEL_MUL55_value		54
#define CGU_PLL1_CTRL_MSEL_MUL56_value		55
#define CGU_PLL1_CTRL_MSEL_MUL57_value		56
#define CGU_PLL1_CTRL_MSEL_MUL58_value		57
#define CGU_PLL1_CTRL_MSEL_MUL59_value		58
#define CGU_PLL1_CTRL_MSEL_MUL60_value		59
#define CGU_PLL1_CTRL_MSEL_MUL61_value		60
#define CGU_PLL1_CTRL_MSEL_MUL62_value		61
#define CGU_PLL1_CTRL_MSEL_MUL63_value		62
#define CGU_PLL1_CTRL_MSEL_MUL64_value		63
#define CGU_PLL1_CTRL_MSEL_MUL65_value		64
#define CGU_PLL1_CTRL_MSEL_MUL66_value		65
#define CGU_PLL1_CTRL_MSEL_MUL67_value		66
#define CGU_PLL1_CTRL_MSEL_MUL68_value		67
#define CGU_PLL1_CTRL_MSEL_MUL69_value		68
#define CGU_PLL1_CTRL_MSEL_MUL70_value		69
#define CGU_PLL1_CTRL_MSEL_MUL71_value		70
#define CGU_PLL1_CTRL_MSEL_MUL72_value		71
#define CGU_PLL1_CTRL_MSEL_MUL73_value		72
#define CGU_PLL1_CTRL_MSEL_MUL74_value		73
#define CGU_PLL1_CTRL_MSEL_MUL75_value		74
#define CGU_PLL1_CTRL_MSEL_MUL76_value		75
#define CGU_PLL1_CTRL_MSEL_MUL77_value		76
#define CGU_PLL1_CTRL_MSEL_MUL78_value		77
#define CGU_PLL1_CTRL_MSEL_MUL79_value		78
#define CGU_PLL1_CTRL_MSEL_MUL80_value		79
#define CGU_PLL1_CTRL_MSEL_MUL81_value		80
#define CGU_PLL1_CTRL_MSEL_MUL82_value		81
#define CGU_PLL1_CTRL_MSEL_MUL83_value		82
#define CGU_PLL1_CTRL_MSEL_MUL84_value		83
#define CGU_PLL1_CTRL_MSEL_MUL85_value		84
#define CGU_PLL1_CTRL_MSEL_MUL86_value		85
#define CGU_PLL1_CTRL_MSEL_MUL87_value		86
#define CGU_PLL1_CTRL_MSEL_MUL88_value		87
#define CGU_PLL1_CTRL_MSEL_MUL89_value		88
#define CGU_PLL1_CTRL_MSEL_MUL90_value		89
#define CGU_PLL1_CTRL_MSEL_MUL91_value		90
#define CGU_PLL1_CTRL_MSEL_MUL92_value		91
#define CGU_PLL1_CTRL_MSEL_MUL93_value		92
#define CGU_PLL1_CTRL_MSEL_MUL94_value		93
#define CGU_PLL1_CTRL_MSEL_MUL95_value		94
#define CGU_PLL1_CTRL_MSEL_MUL96_value		95
#define CGU_PLL1_CTRL_MSEL_MUL97_value		96
#define CGU_PLL1_CTRL_MSEL_MUL98_value		97
#define CGU_PLL1_CTRL_MSEL_MUL99_value		98
#define CGU_PLL1_CTRL_MSEL_MUL100_value		99
#define CGU_PLL1_CTRL_MSEL_MUL101_value		100
#define CGU_PLL1_CTRL_MSEL_MUL102_value		101
#define CGU_PLL1_CTRL_MSEL_MUL103_value		102
#define CGU_PLL1_CTRL_MSEL_MUL104_value		103
#define CGU_PLL1_CTRL_MSEL_MUL105_value		104
#define CGU_PLL1_CTRL_MSEL_MUL106_value		105
#define CGU_PLL1_CTRL_MSEL_MUL107_value		106
#define CGU_PLL1_CTRL_MSEL_MUL108_value		107
#define CGU_PLL1_CTRL_MSEL_MUL109_value		108
#define CGU_PLL1_CTRL_MSEL_MUL110_value		109
#define CGU_PLL1_CTRL_MSEL_MUL111_value		110
#define CGU_PLL1_CTRL_MSEL_MUL112_value		111
#define CGU_PLL1_CTRL_MSEL_MUL113_value		112
#define CGU_PLL1_CTRL_MSEL_MUL114_value		113
#define CGU_PLL1_CTRL_MSEL_MUL115_value		114
#define CGU_PLL1_CTRL_MSEL_MUL116_value		115
#define CGU_PLL1_CTRL_MSEL_MUL117_value		116
#define CGU_PLL1_CTRL_MSEL_MUL118_value		117
#define CGU_PLL1_CTRL_MSEL_MUL119_value		118
#define CGU_PLL1_CTRL_MSEL_MUL120_value		119
#define CGU_PLL1_CTRL_MSEL_MUL121_value		120
#define CGU_PLL1_CTRL_MSEL_MUL122_value		121
#define CGU_PLL1_CTRL_MSEL_MUL123_value		122
#define CGU_PLL1_CTRL_MSEL_MUL124_value		123
#define CGU_PLL1_CTRL_MSEL_MUL125_value		124
#define CGU_PLL1_CTRL_MSEL_MUL126_value		125
#define CGU_PLL1_CTRL_MSEL_MUL127_value		126
#define CGU_PLL1_CTRL_MSEL_MUL128_value		127
#define CGU_PLL1_CTRL_MSEL_MUL129_value		128
#define CGU_PLL1_CTRL_MSEL_MUL130_value		129
#define CGU_PLL1_CTRL_MSEL_MUL131_value		130
#define CGU_PLL1_CTRL_MSEL_MUL132_value		131
#define CGU_PLL1_CTRL_MSEL_MUL133_value		132
#define CGU_PLL1_CTRL_MSEL_MUL134_value		133
#define CGU_PLL1_CTRL_MSEL_MUL135_value		134
#define CGU_PLL1_CTRL_MSEL_MUL136_value		135
#define CGU_PLL1_CTRL_MSEL_MUL137_value		136
#define CGU_PLL1_CTRL_MSEL_MUL138_value		137
#define CGU_PLL1_CTRL_MSEL_MUL139_value		138
#define CGU_PLL1_CTRL_MSEL_MUL140_value		139
#define CGU_PLL1_CTRL_MSEL_MUL141_value		140
#define CGU_PLL1_CTRL_MSEL_MUL142_value		141
#define CGU_PLL1_CTRL_MSEL_MUL143_value		142
#define CGU_PLL1_CTRL_MSEL_MUL144_value		143
#define CGU_PLL1_CTRL_MSEL_MUL145_value		144
#define CGU_PLL1_CTRL_MSEL_MUL146_value		145
#define CGU_PLL1_CTRL_MSEL_MUL147_value		146
#define CGU_PLL1_CTRL_MSEL_MUL148_value		147
#define CGU_PLL1_CTRL_MSEL_MUL149_value		148
#define CGU_PLL1_CTRL_MSEL_MUL150_value		149
#define CGU_PLL1_CTRL_MSEL_MUL151_value		150
#define CGU_PLL1_CTRL_MSEL_MUL152_value		151
#define CGU_PLL1_CTRL_MSEL_MUL153_value		152
#define CGU_PLL1_CTRL_MSEL_MUL154_value		153
#define CGU_PLL1_CTRL_MSEL_MUL155_value		154
#define CGU_PLL1_CTRL_MSEL_MUL156_value		155
#define CGU_PLL1_CTRL_MSEL_MUL157_value		156
#define CGU_PLL1_CTRL_MSEL_MUL158_value		157
#define CGU_PLL1_CTRL_MSEL_MUL159_value		158
#define CGU_PLL1_CTRL_MSEL_MUL160_value		159
#define CGU_PLL1_CTRL_MSEL_MUL161_value		160
#define CGU_PLL1_CTRL_MSEL_MUL162_value		161
#define CGU_PLL1_CTRL_MSEL_MUL163_value		162
#define CGU_PLL1_CTRL_MSEL_MUL164_value		163
#define CGU_PLL1_CTRL_MSEL_MUL165_value		164
#define CGU_PLL1_CTRL_MSEL_MUL166_value		165
#define CGU_PLL1_CTRL_MSEL_MUL167_value		166
#define CGU_PLL1_CTRL_MSEL_MUL168_value		167
#define CGU_PLL1_CTRL_MSEL_MUL169_value		168
#define CGU_PLL1_CTRL_MSEL_MUL170_value		169
#define CGU_PLL1_CTRL_MSEL_MUL171_value		170
#define CGU_PLL1_CTRL_MSEL_MUL172_value		171
#define CGU_PLL1_CTRL_MSEL_MUL173_value		172
#define CGU_PLL1_CTRL_MSEL_MUL174_value		173
#define CGU_PLL1_CTRL_MSEL_MUL175_value		174
#define CGU_PLL1_CTRL_MSEL_MUL176_value		175
#define CGU_PLL1_CTRL_MSEL_MUL177_value		176
#define CGU_PLL1_CTRL_MSEL_MUL178_value		177
#define CGU_PLL1_CTRL_MSEL_MUL179_value		178
#define CGU_PLL1_CTRL_MSEL_MUL180_value		179
#define CGU_PLL1_CTRL_MSEL_MUL181_value		180
#define CGU_PLL1_CTRL_MSEL_MUL182_value		181
#define CGU_PLL1_CTRL_MSEL_MUL183_value		182
#define CGU_PLL1_CTRL_MSEL_MUL184_value		183
#define CGU_PLL1_CTRL_MSEL_MUL185_value		184
#define CGU_PLL1_CTRL_MSEL_MUL186_value		185
#define CGU_PLL1_CTRL_MSEL_MUL187_value		186
#define CGU_PLL1_CTRL_MSEL_MUL188_value		187
#define CGU_PLL1_CTRL_MSEL_MUL189_value		188
#define CGU_PLL1_CTRL_MSEL_MUL190_value		189
#define CGU_PLL1_CTRL_MSEL_MUL191_value		190
#define CGU_PLL1_CTRL_MSEL_MUL192_value		191
#define CGU_PLL1_CTRL_MSEL_MUL193_value		192
#define CGU_PLL1_CTRL_MSEL_MUL194_value		193
#define CGU_PLL1_CTRL_MSEL_MUL195_value		194
#define CGU_PLL1_CTRL_MSEL_MUL196_value		195
#define CGU_PLL1_CTRL_MSEL_MUL197_value		196
#define CGU_PLL1_CTRL_MSEL_MUL198_value		197
#define CGU_PLL1_CTRL_MSEL_MUL199_value		198
#define CGU_PLL1_CTRL_MSEL_MUL200_value		199
#define CGU_PLL1_CTRL_MSEL_MUL201_value		200
#define CGU_PLL1_CTRL_MSEL_MUL202_value		201
#define CGU_PLL1_CTRL_MSEL_MUL203_value		202
#define CGU_PLL1_CTRL_MSEL_MUL204_value		203
#define CGU_PLL1_CTRL_MSEL_MUL205_value		204
#define CGU_PLL1_CTRL_MSEL_MUL206_value		205
#define CGU_PLL1_CTRL_MSEL_MUL207_value		206
#define CGU_PLL1_CTRL_MSEL_MUL208_value		207
#define CGU_PLL1_CTRL_MSEL_MUL209_value		208
#define CGU_PLL1_CTRL_MSEL_MUL210_value		209
#define CGU_PLL1_CTRL_MSEL_MUL211_value		210
#define CGU_PLL1_CTRL_MSEL_MUL212_value		211
#define CGU_PLL1_CTRL_MSEL_MUL213_value		212
#define CGU_PLL1_CTRL_MSEL_MUL214_value		213
#define CGU_PLL1_CTRL_MSEL_MUL215_value		214
#define CGU_PLL1_CTRL_MSEL_MUL216_value		215
#define CGU_PLL1_CTRL_MSEL_MUL217_value		216
#define CGU_PLL1_CTRL_MSEL_MUL218_value		217
#define CGU_PLL1_CTRL_MSEL_MUL219_value		218
#define CGU_PLL1_CTRL_MSEL_MUL220_value		219
#define CGU_PLL1_CTRL_MSEL_MUL221_value		220
#define CGU_PLL1_CTRL_MSEL_MUL222_value		221
#define CGU_PLL1_CTRL_MSEL_MUL223_value		222
#define CGU_PLL1_CTRL_MSEL_MUL224_value		223
#define CGU_PLL1_CTRL_MSEL_MUL225_value		224
#define CGU_PLL1_CTRL_MSEL_MUL226_value		225
#define CGU_PLL1_CTRL_MSEL_MUL227_value		226
#define CGU_PLL1_CTRL_MSEL_MUL228_value		227
#define CGU_PLL1_CTRL_MSEL_MUL229_value		228
#define CGU_PLL1_CTRL_MSEL_MUL230_value		229
#define CGU_PLL1_CTRL_MSEL_MUL231_value		230
#define CGU_PLL1_CTRL_MSEL_MUL232_value		231
#define CGU_PLL1_CTRL_MSEL_MUL233_value		232
#define CGU_PLL1_CTRL_MSEL_MUL234_value		233
#define CGU_PLL1_CTRL_MSEL_MUL235_value		234
#define CGU_PLL1_CTRL_MSEL_MUL236_value		235
#define CGU_PLL1_CTRL_MSEL_MUL237_value		236
#define CGU_PLL1_CTRL_MSEL_MUL238_value		237
#define CGU_PLL1_CTRL_MSEL_MUL239_value		238
#define CGU_PLL1_CTRL_MSEL_MUL240_value		239
#define CGU_PLL1_CTRL_MSEL_MUL241_value		240
#define CGU_PLL1_CTRL_MSEL_MUL242_value		241
#define CGU_PLL1_CTRL_MSEL_MUL243_value		242
#define CGU_PLL1_CTRL_MSEL_MUL244_value		243
#define CGU_PLL1_CTRL_MSEL_MUL245_value		244
#define CGU_PLL1_CTRL_MSEL_MUL246_value		245
#define CGU_PLL1_CTRL_MSEL_MUL247_value		246
#define CGU_PLL1_CTRL_MSEL_MUL248_value		247
#define CGU_PLL1_CTRL_MSEL_MUL249_value		248
#define CGU_PLL1_CTRL_MSEL_MUL250_value		249
#define CGU_PLL1_CTRL_MSEL_MUL251_value		250
#define CGU_PLL1_CTRL_MSEL_MUL252_value		251
#define CGU_PLL1_CTRL_MSEL_MUL253_value		252
#define CGU_PLL1_CTRL_MSEL_MUL254_value		253
#define CGU_PLL1_CTRL_MSEL_MUL255_value		254
#define CGU_PLL1_CTRL_MSEL_MUL256_value		255

#define CGU_PLL1_CTRL_MSEL_MUL1				(CGU_PLL1_CTRL_MSEL_MUL1_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL2				(CGU_PLL1_CTRL_MSEL_MUL2_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL3				(CGU_PLL1_CTRL_MSEL_MUL3_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL4				(CGU_PLL1_CTRL_MSEL_MUL4_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL5				(CGU_PLL1_CTRL_MSEL_MUL5_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL6				(CGU_PLL1_CTRL_MSEL_MUL6_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL7				(CGU_PLL1_CTRL_MSEL_MUL7_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL8				(CGU_PLL1_CTRL_MSEL_MUL8_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL9				(CGU_PLL1_CTRL_MSEL_MUL9_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL10			(CGU_PLL1_CTRL_MSEL_MUL10_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL11			(CGU_PLL1_CTRL_MSEL_MUL11_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL12			(CGU_PLL1_CTRL_MSEL_MUL12_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL13			(CGU_PLL1_CTRL_MSEL_MUL13_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL14			(CGU_PLL1_CTRL_MSEL_MUL14_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL15			(CGU_PLL1_CTRL_MSEL_MUL15_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL16			(CGU_PLL1_CTRL_MSEL_MUL16_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL17			(CGU_PLL1_CTRL_MSEL_MUL17_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL18			(CGU_PLL1_CTRL_MSEL_MUL18_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL19			(CGU_PLL1_CTRL_MSEL_MUL19_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL20			(CGU_PLL1_CTRL_MSEL_MUL20_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL21			(CGU_PLL1_CTRL_MSEL_MUL21_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL22			(CGU_PLL1_CTRL_MSEL_MUL22_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL23			(CGU_PLL1_CTRL_MSEL_MUL23_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL24			(CGU_PLL1_CTRL_MSEL_MUL24_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL25			(CGU_PLL1_CTRL_MSEL_MUL25_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL26			(CGU_PLL1_CTRL_MSEL_MUL26_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL27			(CGU_PLL1_CTRL_MSEL_MUL27_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL28			(CGU_PLL1_CTRL_MSEL_MUL28_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL29			(CGU_PLL1_CTRL_MSEL_MUL29_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL30			(CGU_PLL1_CTRL_MSEL_MUL30_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL31			(CGU_PLL1_CTRL_MSEL_MUL31_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL32			(CGU_PLL1_CTRL_MSEL_MUL32_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL33			(CGU_PLL1_CTRL_MSEL_MUL33_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL34			(CGU_PLL1_CTRL_MSEL_MUL34_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL35			(CGU_PLL1_CTRL_MSEL_MUL35_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL36			(CGU_PLL1_CTRL_MSEL_MUL36_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL37			(CGU_PLL1_CTRL_MSEL_MUL37_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL38			(CGU_PLL1_CTRL_MSEL_MUL38_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL39			(CGU_PLL1_CTRL_MSEL_MUL39_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL40			(CGU_PLL1_CTRL_MSEL_MUL40_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL41			(CGU_PLL1_CTRL_MSEL_MUL41_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL42			(CGU_PLL1_CTRL_MSEL_MUL42_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL43			(CGU_PLL1_CTRL_MSEL_MUL43_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL44			(CGU_PLL1_CTRL_MSEL_MUL44_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL45			(CGU_PLL1_CTRL_MSEL_MUL45_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL46			(CGU_PLL1_CTRL_MSEL_MUL46_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL47			(CGU_PLL1_CTRL_MSEL_MUL47_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL48			(CGU_PLL1_CTRL_MSEL_MUL48_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL49			(CGU_PLL1_CTRL_MSEL_MUL49_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL50			(CGU_PLL1_CTRL_MSEL_MUL50_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL51			(CGU_PLL1_CTRL_MSEL_MUL51_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL52			(CGU_PLL1_CTRL_MSEL_MUL52_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL53			(CGU_PLL1_CTRL_MSEL_MUL53_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL54			(CGU_PLL1_CTRL_MSEL_MUL54_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL55			(CGU_PLL1_CTRL_MSEL_MUL55_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL56			(CGU_PLL1_CTRL_MSEL_MUL56_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL57			(CGU_PLL1_CTRL_MSEL_MUL57_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL58			(CGU_PLL1_CTRL_MSEL_MUL58_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL59			(CGU_PLL1_CTRL_MSEL_MUL59_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL60			(CGU_PLL1_CTRL_MSEL_MUL60_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL61			(CGU_PLL1_CTRL_MSEL_MUL61_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL62			(CGU_PLL1_CTRL_MSEL_MUL62_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL63			(CGU_PLL1_CTRL_MSEL_MUL63_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL64			(CGU_PLL1_CTRL_MSEL_MUL64_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL65			(CGU_PLL1_CTRL_MSEL_MUL65_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL66			(CGU_PLL1_CTRL_MSEL_MUL66_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL67			(CGU_PLL1_CTRL_MSEL_MUL67_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL68			(CGU_PLL1_CTRL_MSEL_MUL68_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL69			(CGU_PLL1_CTRL_MSEL_MUL69_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL70			(CGU_PLL1_CTRL_MSEL_MUL70_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL71			(CGU_PLL1_CTRL_MSEL_MUL71_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL72			(CGU_PLL1_CTRL_MSEL_MUL72_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL73			(CGU_PLL1_CTRL_MSEL_MUL73_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL74			(CGU_PLL1_CTRL_MSEL_MUL74_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL75			(CGU_PLL1_CTRL_MSEL_MUL75_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL76			(CGU_PLL1_CTRL_MSEL_MUL76_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL77			(CGU_PLL1_CTRL_MSEL_MUL77_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL78			(CGU_PLL1_CTRL_MSEL_MUL78_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL79			(CGU_PLL1_CTRL_MSEL_MUL79_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL80			(CGU_PLL1_CTRL_MSEL_MUL80_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL81			(CGU_PLL1_CTRL_MSEL_MUL81_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL82			(CGU_PLL1_CTRL_MSEL_MUL82_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL83			(CGU_PLL1_CTRL_MSEL_MUL83_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL84			(CGU_PLL1_CTRL_MSEL_MUL84_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL85			(CGU_PLL1_CTRL_MSEL_MUL85_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL86			(CGU_PLL1_CTRL_MSEL_MUL86_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL87			(CGU_PLL1_CTRL_MSEL_MUL87_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL88			(CGU_PLL1_CTRL_MSEL_MUL88_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL89			(CGU_PLL1_CTRL_MSEL_MUL89_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL90			(CGU_PLL1_CTRL_MSEL_MUL90_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL91			(CGU_PLL1_CTRL_MSEL_MUL91_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL92			(CGU_PLL1_CTRL_MSEL_MUL92_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL93			(CGU_PLL1_CTRL_MSEL_MUL93_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL94			(CGU_PLL1_CTRL_MSEL_MUL94_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL95			(CGU_PLL1_CTRL_MSEL_MUL95_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL96			(CGU_PLL1_CTRL_MSEL_MUL96_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL97			(CGU_PLL1_CTRL_MSEL_MUL97_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL98			(CGU_PLL1_CTRL_MSEL_MUL98_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL99			(CGU_PLL1_CTRL_MSEL_MUL99_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL100			(CGU_PLL1_CTRL_MSEL_MUL100_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL101			(CGU_PLL1_CTRL_MSEL_MUL101_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL102			(CGU_PLL1_CTRL_MSEL_MUL102_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL103			(CGU_PLL1_CTRL_MSEL_MUL103_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL104			(CGU_PLL1_CTRL_MSEL_MUL104_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL105			(CGU_PLL1_CTRL_MSEL_MUL105_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL106			(CGU_PLL1_CTRL_MSEL_MUL106_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL107			(CGU_PLL1_CTRL_MSEL_MUL107_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL108			(CGU_PLL1_CTRL_MSEL_MUL108_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL109			(CGU_PLL1_CTRL_MSEL_MUL109_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL110			(CGU_PLL1_CTRL_MSEL_MUL110_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL111			(CGU_PLL1_CTRL_MSEL_MUL111_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL112			(CGU_PLL1_CTRL_MSEL_MUL112_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL113			(CGU_PLL1_CTRL_MSEL_MUL113_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL114			(CGU_PLL1_CTRL_MSEL_MUL114_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL115			(CGU_PLL1_CTRL_MSEL_MUL115_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL116			(CGU_PLL1_CTRL_MSEL_MUL116_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL117			(CGU_PLL1_CTRL_MSEL_MUL117_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL118			(CGU_PLL1_CTRL_MSEL_MUL118_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL119			(CGU_PLL1_CTRL_MSEL_MUL119_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL120			(CGU_PLL1_CTRL_MSEL_MUL120_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL121			(CGU_PLL1_CTRL_MSEL_MUL121_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL122			(CGU_PLL1_CTRL_MSEL_MUL122_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL123			(CGU_PLL1_CTRL_MSEL_MUL123_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL124			(CGU_PLL1_CTRL_MSEL_MUL124_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL125			(CGU_PLL1_CTRL_MSEL_MUL125_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL126			(CGU_PLL1_CTRL_MSEL_MUL126_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL127			(CGU_PLL1_CTRL_MSEL_MUL127_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL128			(CGU_PLL1_CTRL_MSEL_MUL128_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL129			(CGU_PLL1_CTRL_MSEL_MUL129_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL130			(CGU_PLL1_CTRL_MSEL_MUL130_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL131			(CGU_PLL1_CTRL_MSEL_MUL131_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL132			(CGU_PLL1_CTRL_MSEL_MUL132_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL133			(CGU_PLL1_CTRL_MSEL_MUL133_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL134			(CGU_PLL1_CTRL_MSEL_MUL134_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL135			(CGU_PLL1_CTRL_MSEL_MUL135_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL136			(CGU_PLL1_CTRL_MSEL_MUL136_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL137			(CGU_PLL1_CTRL_MSEL_MUL137_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL138			(CGU_PLL1_CTRL_MSEL_MUL138_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL139			(CGU_PLL1_CTRL_MSEL_MUL139_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL140			(CGU_PLL1_CTRL_MSEL_MUL140_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL141			(CGU_PLL1_CTRL_MSEL_MUL141_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL142			(CGU_PLL1_CTRL_MSEL_MUL142_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL143			(CGU_PLL1_CTRL_MSEL_MUL143_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL144			(CGU_PLL1_CTRL_MSEL_MUL144_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL145			(CGU_PLL1_CTRL_MSEL_MUL145_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL146			(CGU_PLL1_CTRL_MSEL_MUL146_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL147			(CGU_PLL1_CTRL_MSEL_MUL147_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL148			(CGU_PLL1_CTRL_MSEL_MUL148_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL149			(CGU_PLL1_CTRL_MSEL_MUL149_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL150			(CGU_PLL1_CTRL_MSEL_MUL150_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL151			(CGU_PLL1_CTRL_MSEL_MUL151_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL152			(CGU_PLL1_CTRL_MSEL_MUL152_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL153			(CGU_PLL1_CTRL_MSEL_MUL153_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL154			(CGU_PLL1_CTRL_MSEL_MUL154_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL155			(CGU_PLL1_CTRL_MSEL_MUL155_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL156			(CGU_PLL1_CTRL_MSEL_MUL156_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL157			(CGU_PLL1_CTRL_MSEL_MUL157_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL158			(CGU_PLL1_CTRL_MSEL_MUL158_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL159			(CGU_PLL1_CTRL_MSEL_MUL159_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL160			(CGU_PLL1_CTRL_MSEL_MUL160_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL161			(CGU_PLL1_CTRL_MSEL_MUL161_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL162			(CGU_PLL1_CTRL_MSEL_MUL162_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL163			(CGU_PLL1_CTRL_MSEL_MUL163_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL164			(CGU_PLL1_CTRL_MSEL_MUL164_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL165			(CGU_PLL1_CTRL_MSEL_MUL165_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL166			(CGU_PLL1_CTRL_MSEL_MUL166_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL167			(CGU_PLL1_CTRL_MSEL_MUL167_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL168			(CGU_PLL1_CTRL_MSEL_MUL168_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL169			(CGU_PLL1_CTRL_MSEL_MUL169_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL170			(CGU_PLL1_CTRL_MSEL_MUL170_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL171			(CGU_PLL1_CTRL_MSEL_MUL171_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL172			(CGU_PLL1_CTRL_MSEL_MUL172_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL173			(CGU_PLL1_CTRL_MSEL_MUL173_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL174			(CGU_PLL1_CTRL_MSEL_MUL174_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL175			(CGU_PLL1_CTRL_MSEL_MUL175_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL176			(CGU_PLL1_CTRL_MSEL_MUL176_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL177			(CGU_PLL1_CTRL_MSEL_MUL177_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL178			(CGU_PLL1_CTRL_MSEL_MUL178_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL179			(CGU_PLL1_CTRL_MSEL_MUL179_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL180			(CGU_PLL1_CTRL_MSEL_MUL180_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL181			(CGU_PLL1_CTRL_MSEL_MUL181_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL182			(CGU_PLL1_CTRL_MSEL_MUL182_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL183			(CGU_PLL1_CTRL_MSEL_MUL183_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL184			(CGU_PLL1_CTRL_MSEL_MUL184_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL185			(CGU_PLL1_CTRL_MSEL_MUL185_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL186			(CGU_PLL1_CTRL_MSEL_MUL186_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL187			(CGU_PLL1_CTRL_MSEL_MUL187_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL188			(CGU_PLL1_CTRL_MSEL_MUL188_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL189			(CGU_PLL1_CTRL_MSEL_MUL189_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL190			(CGU_PLL1_CTRL_MSEL_MUL190_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL191			(CGU_PLL1_CTRL_MSEL_MUL191_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL192			(CGU_PLL1_CTRL_MSEL_MUL192_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL193			(CGU_PLL1_CTRL_MSEL_MUL193_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL194			(CGU_PLL1_CTRL_MSEL_MUL194_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL195			(CGU_PLL1_CTRL_MSEL_MUL195_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL196			(CGU_PLL1_CTRL_MSEL_MUL196_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL197			(CGU_PLL1_CTRL_MSEL_MUL197_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL198			(CGU_PLL1_CTRL_MSEL_MUL198_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL199			(CGU_PLL1_CTRL_MSEL_MUL199_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL200			(CGU_PLL1_CTRL_MSEL_MUL200_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL201			(CGU_PLL1_CTRL_MSEL_MUL201_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL202			(CGU_PLL1_CTRL_MSEL_MUL202_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL203			(CGU_PLL1_CTRL_MSEL_MUL203_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL204			(CGU_PLL1_CTRL_MSEL_MUL204_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL205			(CGU_PLL1_CTRL_MSEL_MUL205_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL206			(CGU_PLL1_CTRL_MSEL_MUL206_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL207			(CGU_PLL1_CTRL_MSEL_MUL207_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL208			(CGU_PLL1_CTRL_MSEL_MUL208_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL209			(CGU_PLL1_CTRL_MSEL_MUL209_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL210			(CGU_PLL1_CTRL_MSEL_MUL210_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL211			(CGU_PLL1_CTRL_MSEL_MUL211_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL212			(CGU_PLL1_CTRL_MSEL_MUL212_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL213			(CGU_PLL1_CTRL_MSEL_MUL213_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL214			(CGU_PLL1_CTRL_MSEL_MUL214_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL215			(CGU_PLL1_CTRL_MSEL_MUL215_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL216			(CGU_PLL1_CTRL_MSEL_MUL216_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL217			(CGU_PLL1_CTRL_MSEL_MUL217_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL218			(CGU_PLL1_CTRL_MSEL_MUL218_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL219			(CGU_PLL1_CTRL_MSEL_MUL219_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL220			(CGU_PLL1_CTRL_MSEL_MUL220_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL221			(CGU_PLL1_CTRL_MSEL_MUL221_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL222			(CGU_PLL1_CTRL_MSEL_MUL222_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL223			(CGU_PLL1_CTRL_MSEL_MUL223_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL224			(CGU_PLL1_CTRL_MSEL_MUL224_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL225			(CGU_PLL1_CTRL_MSEL_MUL225_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL226			(CGU_PLL1_CTRL_MSEL_MUL226_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL227			(CGU_PLL1_CTRL_MSEL_MUL227_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL228			(CGU_PLL1_CTRL_MSEL_MUL228_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL229			(CGU_PLL1_CTRL_MSEL_MUL229_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL230			(CGU_PLL1_CTRL_MSEL_MUL230_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL231			(CGU_PLL1_CTRL_MSEL_MUL231_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL232			(CGU_PLL1_CTRL_MSEL_MUL232_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL233			(CGU_PLL1_CTRL_MSEL_MUL233_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL234			(CGU_PLL1_CTRL_MSEL_MUL234_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL235			(CGU_PLL1_CTRL_MSEL_MUL235_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL236			(CGU_PLL1_CTRL_MSEL_MUL236_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL237			(CGU_PLL1_CTRL_MSEL_MUL237_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL238			(CGU_PLL1_CTRL_MSEL_MUL238_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL239			(CGU_PLL1_CTRL_MSEL_MUL239_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL240			(CGU_PLL1_CTRL_MSEL_MUL240_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL241			(CGU_PLL1_CTRL_MSEL_MUL241_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL242			(CGU_PLL1_CTRL_MSEL_MUL242_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL243			(CGU_PLL1_CTRL_MSEL_MUL243_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL244			(CGU_PLL1_CTRL_MSEL_MUL244_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL245			(CGU_PLL1_CTRL_MSEL_MUL245_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL246			(CGU_PLL1_CTRL_MSEL_MUL246_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL247			(CGU_PLL1_CTRL_MSEL_MUL247_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL248			(CGU_PLL1_CTRL_MSEL_MUL248_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL249			(CGU_PLL1_CTRL_MSEL_MUL249_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL250			(CGU_PLL1_CTRL_MSEL_MUL250_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL251			(CGU_PLL1_CTRL_MSEL_MUL251_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL252			(CGU_PLL1_CTRL_MSEL_MUL252_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL253			(CGU_PLL1_CTRL_MSEL_MUL253_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL254			(CGU_PLL1_CTRL_MSEL_MUL254_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL255			(CGU_PLL1_CTRL_MSEL_MUL255_value << CGU_PLL1_CTRL_MSEL_Pos)
#define CGU_PLL1_CTRL_MSEL_MUL256			(CGU_PLL1_CTRL_MSEL_MUL256_value << CGU_PLL1_CTRL_MSEL_Pos)


#endif	// HDR_HDR_I2C_H_
